--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.2

\connect api_postgres

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_key; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.access_key (
    id bigint NOT NULL,
    key character varying(20) NOT NULL,
    secret character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    valid_through timestamp without time zone NOT NULL,
    role character varying(255) DEFAULT 'NONE'::character varying NOT NULL,
    revoked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.access_key OWNER TO apiuser;

--
-- Name: access_key_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.access_key ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.agent (
    agent_id character varying(64) NOT NULL,
    tags text,
    data_sources text,
    created_date timestamp without time zone NOT NULL,
    updated_date timestamp without time zone NOT NULL,
    latest_heartbeat timestamp without time zone NOT NULL
);


ALTER TABLE public.agent OWNER TO apiuser;

--
-- Name: agent_execution; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.agent_execution (
    workflow_run_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_date timestamp without time zone NOT NULL,
    agent_id character varying(64) NOT NULL,
    status character varying(255) NOT NULL
);


ALTER TABLE public.agent_execution OWNER TO apiuser;

--
-- Name: approval_log; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.approval_log (
    id bigint NOT NULL,
    approval_status character varying(16) NOT NULL,
    description character varying(255),
    workflow_id bigint NOT NULL,
    user_name character varying(255),
    user_id bigint NOT NULL,
    change_timestamp timestamp without time zone NOT NULL
);


ALTER TABLE public.approval_log OWNER TO apiuser;

--
-- Name: approval_log_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.approval_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    user_id bigint,
    created_date timestamp without time zone NOT NULL,
    url character varying(511),
    method character varying(32),
    label character varying(255)
);


ALTER TABLE public.audit_log OWNER TO apiuser;

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: connection_to_spawn_ddl; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.connection_to_spawn_ddl (
    database_connection_id bigint NOT NULL,
    spawn_ddl_id bigint NOT NULL
);


ALTER TABLE public.connection_to_spawn_ddl OWNER TO apiuser;

--
-- Name: database_connection; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.database_connection (
    id bigint NOT NULL,
    sql_dialect character varying(255) DEFAULT 'NONE'::character varying NOT NULL,
    host character varying(255),
    port integer,
    "user" character varying(255),
    password character varying(255),
    name character varying(255) DEFAULT NULL::character varying,
    jdbc_url character varying(1000) DEFAULT NULL::character varying,
    auth_type character varying(255) DEFAULT 'CREDENTIALS'::character varying NOT NULL,
    availability character varying(255) DEFAULT 'PRIVATE'::character varying NOT NULL,
    created_by bigint NOT NULL,
    created_date timestamp without time zone,
    updated_date timestamp without time zone,
    access_level character varying(255) DEFAULT 'READ_ONLY'::character varying NOT NULL,
    password_salt bytea,
    vaulted_username json,
    vaulted_password json,
    data_source_tag character varying(255),
    spawned_db_id uuid
);


ALTER TABLE public.database_connection OWNER TO apiuser;

--
-- Name: database_connection_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.database_connection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.database_connection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO apiuser;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO apiuser;

--
-- Name: license; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.license (
    id bigint NOT NULL,
    license text NOT NULL
);


ALTER TABLE public.license OWNER TO apiuser;

--
-- Name: secretmanager_setup; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.secretmanager_setup (
    id character varying(16) NOT NULL,
    parameters json NOT NULL
);


ALTER TABLE public.secretmanager_setup OWNER TO apiuser;

--
-- Name: spawn_ddl; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.spawn_ddl (
    id bigint NOT NULL,
    database_vendor character varying(64) DEFAULT 'NONE'::character varying NOT NULL,
    sql_statement_separator character varying(10) DEFAULT 'NONE'::character varying NOT NULL,
    ddl text NOT NULL,
    database_name character varying(255) DEFAULT 'NONE'::character varying NOT NULL
);


ALTER TABLE public.spawn_ddl OWNER TO apiuser;

--
-- Name: spawn_ddl_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.spawn_ddl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_ddl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tag; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.tag (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.tag OWNER TO apiuser;

--
-- Name: tag_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tag_to_workflow; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.tag_to_workflow (
    tag_id bigint NOT NULL,
    workflow_id bigint NOT NULL
);


ALTER TABLE public.tag_to_workflow OWNER TO apiuser;

--
-- Name: ui_table_layout; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.ui_table_layout (
    id bigint NOT NULL,
    name character varying(255),
    created_by bigint NOT NULL
);


ALTER TABLE public.ui_table_layout OWNER TO apiuser;

--
-- Name: ui_table_layout_content; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.ui_table_layout_content (
    id bigint NOT NULL,
    layout_id bigint NOT NULL,
    component_name character varying(32) NOT NULL,
    column_name character varying(255) NOT NULL,
    flag boolean DEFAULT false NOT NULL,
    filter_value character varying(1024)
);


ALTER TABLE public.ui_table_layout_content OWNER TO apiuser;

--
-- Name: ui_table_layout_content_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.ui_table_layout_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ui_table_layout_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ui_table_layout_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.ui_table_layout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ui_table_layout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    name character varying(255),
    password character varying(255),
    enabled boolean,
    fullname character varying(255) DEFAULT ''::character varying NOT NULL,
    organization character varying(255) DEFAULT ''::character varying NOT NULL,
    role character varying(255) DEFAULT 'NONE'::character varying NOT NULL,
    change_password_on_next_login boolean DEFAULT true NOT NULL,
    auth_provider character varying(15) NOT NULL
);


ALTER TABLE public."user" OWNER TO apiuser;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.workflow (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_date timestamp without time zone,
    updated_date timestamp without time zone,
    input_connection_id bigint,
    output_connection_id bigint,
    user_id bigint NOT NULL,
    config text,
    workflow_storage_type character varying(10) NOT NULL,
    git_uri character varying(1000),
    git_path character varying(1000),
    git_branch character varying(1000),
    availability_status character varying(16),
    source_pool_size integer,
    target_pool_size integer
);


ALTER TABLE public.workflow OWNER TO apiuser;

--
-- Name: workflow_activity_log; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.workflow_activity_log (
    id bigint NOT NULL,
    workflow_id bigint NOT NULL,
    user_name character varying(255),
    user_id bigint NOT NULL,
    change_timestamp timestamp without time zone NOT NULL,
    description character varying(255),
    category character varying(255)
);


ALTER TABLE public.workflow_activity_log OWNER TO apiuser;

--
-- Name: workflow_activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.workflow_activity_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.workflow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_run; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.workflow_run (
    id bigint NOT NULL,
    workflow_id bigint,
    workflow_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_date timestamp without time zone NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    user_id bigint,
    config text,
    error_stacktrace text,
    error_message text,
    user_name character varying(255),
    use_agents boolean DEFAULT false NOT NULL
);


ALTER TABLE public.workflow_run OWNER TO apiuser;

--
-- Name: workflow_run_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.workflow_run ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_run_step; Type: TABLE; Schema: public; Owner: apiuser
--

CREATE TABLE public.workflow_run_step (
    id bigint NOT NULL,
    workflow_run_id bigint,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone
);


ALTER TABLE public.workflow_run_step OWNER TO apiuser;

--
-- Name: workflow_run_step_id_seq; Type: SEQUENCE; Schema: public; Owner: apiuser
--

ALTER TABLE public.workflow_run_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_run_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: access_key; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: agent; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: agent_execution; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: approval_log; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: connection_to_spawn_ddl; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: database_connection; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.database_connection VALUES (1, 'POSTGRES', NULL, NULL, 'apiuser', 'NOO9ZHI45HhaHBoLwMNkTw==', 'input', 'jdbc:postgresql://transformed_db:5432/input_source', 'CREDENTIALS', 'PRIVATE', 1, '2022-12-29 14:42:37.177302', '2022-12-29 14:42:37.177321', 'READ_ONLY', '\x2499b374f7f85719b43bbbb8b4b2e5de', NULL, NULL, NULL, NULL);
INSERT INTO public.database_connection VALUES (2, 'POSTGRES', NULL, NULL, 'apiuser', 'eyxyfmqbHHYlH0NZZ/6Gew==', 'output', 'jdbc:postgresql://transformed_db:5432/output_source', 'CREDENTIALS', 'PRIVATE', 1, '2022-12-29 14:42:54.435254', '2022-12-29 14:42:59.918208', 'READ_AND_WRITE', '\xc468edd2487c4a2a5201aedd16c0205e', NULL, NULL, NULL, NULL);


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.databasechangelog VALUES ('1644305159788-1', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.070581', 1, 'EXECUTED', '9:f8db6c380236dd8c371ca6ca661f3e87', 'createTable tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-2', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.094083', 2, 'EXECUTED', '9:817e7196d08061d298d1974f6ee6ae19', 'createTable tableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-3', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.11008', 3, 'EXECUTED', '9:f57f0ae2391e95d94d59e91dc0f08c35', 'createIndex indexName=database_connection_uidx, tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-4', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.125187', 4, 'EXECUTED', '9:6b39ce2177b30805555d6c3596da44bb', 'createIndex indexName=user_name_uidx, tableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-5', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.144008', 5, 'EXECUTED', '9:910c9d194284071b58f72c944405646d', 'createTable tableName=workflow', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-6', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.158742', 6, 'EXECUTED', '9:ec919dfe5c85a027d2bce4d025812f9e', 'addForeignKeyConstraint baseTableName=database_connection, constraintName=database_connection_created_by_fkey, referencedTableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-7', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.175616', 7, 'EXECUTED', '9:1358c106070b4f64f028cd88cee362d7', 'addForeignKeyConstraint baseTableName=workflow, constraintName=workflow_input_connection_id_fkey, referencedTableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-8', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.189609', 8, 'EXECUTED', '9:330529a08fb23a3fdb9461f065f4c084', 'addForeignKeyConstraint baseTableName=workflow, constraintName=workflow_output_connection_id_fkey, referencedTableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('1644305159788-9', 'vitaly (generated)', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.206588', 9, 'EXECUTED', '9:802288e3f92daf119b51d827c4f1a41b', 'addForeignKeyConstraint baseTableName=workflow, constraintName=workflow_user_id_fkey, referencedTableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('41-workflow-run', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.22737', 10, 'EXECUTED', '9:20a15995ae1f96bb0849a292346fccbd', 'addColumn tableName=workflow', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('49-connection-availability-1', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.238888', 11, 'EXECUTED', '9:f5f344381647fcb496635789fd2590fc', 'renameColumn newColumnName=availability, oldColumnName=access_level, tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('49-connection-availability-2', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.249017', 12, 'EXECUTED', '9:61b098b7bb1164966c9874a38e1c8781', 'addColumn tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('41-workflow-run-fixes-1', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.261855', 13, 'EXECUTED', '9:3300567739bb4479bcb81922260ea0b1', 'renameColumn newColumnName=sql_dialect, oldColumnName=type, tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('41-workflow-run-fixes-2', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.278265', 14, 'EXECUTED', '9:c549b70efecac7e04b528ba2bd8fb260', 'renameColumn newColumnName=user, oldColumnName=user_name, tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('84-encrypt-password-1', 'vitaly', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.291053', 15, 'EXECUTED', '9:1854238269010ae3f51c3033564afd21', 'addColumn tableName=database_connection', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('74-password-changing', 'roman', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.30362', 16, 'EXECUTED', '9:0632e78526165e64b2202f67ffbf421c', 'addColumn tableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('5-audit', 'mark', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.361699', 17, 'EXECUTED', '9:0d706db81926b2a40f3592bad960df79', 'createTable tableName=audit_log; addForeignKeyConstraint baseTableName=audit_log, constraintName=audit_log_user_id_fkey, referencedTableName=user', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('fix-1141', 'ivan', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.388929', 18, 'EXECUTED', '9:20e9bbff3280e467202a0a95979221c8', 'createTable tableName=approval_log', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('fix-1279', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2022-12-29 14:41:38.431809', 19, 'EXECUTED', '9:037101a2e9819184a26759a53bc814c9', 'createTable tableName=workflow_run; createTable tableName=workflow_run_step; addForeignKeyConstraint baseTableName=workflow_run_step, constraintName=workflow_run_step_workflow_run_id_fkey, referencedTableName=workflow_run', '', NULL, '4.18.0', NULL, NULL, '2324897852');
INSERT INTO public.databasechangelog VALUES ('fix-1360', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-05-02 14:33:20.51238', 20, 'EXECUTED', '9:cac1b31537c1fe7127f4cb6b3a1e1d67', 'createTable tableName=workflow_activity_log', '', NULL, '4.21.1', NULL, NULL, '3038000330');
INSERT INTO public.databasechangelog VALUES ('fix-1293', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-05-02 14:33:20.527961', 21, 'EXECUTED', '9:e6edfc1d792a8fcb3934901229f88fe9', 'dropForeignKeyConstraint baseTableName=approval_log, constraintName=approval_log_workflow_fk', '', NULL, '4.21.1', NULL, NULL, '3038000330');
INSERT INTO public.databasechangelog VALUES ('run-collector', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-05-02 14:33:20.552917', 22, 'EXECUTED', '9:290fb3204e239905185037d8e98b62f9', 'createTable tableName=run_log', '', NULL, '4.21.1', NULL, NULL, '3038000330');
INSERT INTO public.databasechangelog VALUES ('collector-additional-fields', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.651508', 23, 'EXECUTED', '9:7a207afab93ca68c0a55b32488647d29', 'addColumn tableName=run_log', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('license-table', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.677895', 24, 'EXECUTED', '9:8614be84f9b1c3da52d5930ace525356', 'createTable tableName=license', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('add-workflow-type-column', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.690405', 25, 'EXECUTED', '9:25604895b8d84b0c420c85a683e994eb', 'addColumn tableName=workflow; addNotNullConstraint columnName=workflow_type, tableName=workflow', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('add-auth-provider-column', 'mstepachev@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.698839', 26, 'EXECUTED', '9:464543dbf696eef697f1881396af2ae2', 'addColumn tableName=user', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('expand-credentials-column', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.707347', 27, 'EXECUTED', '9:8b0abde683176d94584973b761b13bbb', 'addColumn tableName=database_connection', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('add-secretmanagers-setup', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2023-08-31 19:09:25.725423', 28, 'EXECUTED', '9:33a5d3576de9bd03ddb1d879f889b7bc', 'createTable tableName=secretmanager_setup', '', NULL, '4.22.0', NULL, NULL, '3508965505');
INSERT INTO public.databasechangelog VALUES ('add-git-fields', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.025853', 29, 'EXECUTED', '9:2463d3393cae087ec2f5c5d3083ffc0a', 'addColumn tableName=workflow; addNotNullConstraint columnName=workflow_storage_type, tableName=workflow', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('add-username-to-workflow-run', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.043462', 30, 'EXECUTED', '9:280f804cb748e7f7943b09f68a8470cf', 'addColumn tableName=workflow_run', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('add-user-id-index-for-workflow', 'mstepachev@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.061511', 31, 'EXECUTED', '9:9a44ba94386aabf67d9d0cf340043da1', 'createIndex indexName=workflow_user_id_idx, tableName=workflow', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('tdk-on-agents', 'alex.bichuk@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.122403', 32, 'EXECUTED', '9:eca5391bf6168d870b7182292f5e150b', 'addColumn tableName=workflow_run; createTable tableName=agent; createTable tableName=agent_execution; addForeignKeyConstraint baseTableName=agent_execution, constraintName=agent_execution_workflow_run_id_fkey, referencedTableName=workflow_run; add...', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('add-spawned-id', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.136501', 33, 'EXECUTED', '9:82d6e47d71c0a76350c06dbfeff0ae42', 'addColumn tableName=database_connection', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('auth-provider-default-non-null-value', 'mstepachev@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.151647', 34, 'EXECUTED', '9:7381d5ead296bbc9fb54b9951e3858df', 'addNotNullConstraint columnName=auth_provider, tableName=user', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('add-tags-for-workflow', 'alex.bichuk@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.181091', 35, 'EXECUTED', '9:5b04a868b24b23005a51b359d84a60a5', 'createTable tableName=tag; createTable tableName=tag_to_workflow', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('cascade-tags-drop-for-workflow', 'alex.bichuk@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.20314', 36, 'EXECUTED', '9:356ad4fbf3d0bb068bf951a00e4f9772', 'dropForeignKeyConstraint baseTableName=tag_to_workflow, constraintName=fk_tag_to_workflow_tag; dropForeignKeyConstraint baseTableName=tag_to_workflow, constraintName=fk_tag_to_workflow_workflow; addForeignKeyConstraint baseTableName=tag_to_workflo...', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('access-keys', 'vitaly@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.230858', 37, 'EXECUTED', '9:86a32693cf9a2636efae98a6bf506b23', 'createTable tableName=access_key; addForeignKeyConstraint baseTableName=access_key, constraintName=fk_access_keys_user_id, referencedTableName=user', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('respawning-database', 'alex.bichuk@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.270589', 38, 'EXECUTED', '9:3a32c9f5621ffb513c005c17c28fabfb', 'createTable tableName=spawn_ddl; createTable tableName=connection_to_spawn_ddl; addForeignKeyConstraint baseTableName=connection_to_spawn_ddl, constraintName=fk_connection_to_spawn_ddl_to_database_connection, referencedTableName=database_connectio...', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('remove-run-log', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.287444', 39, 'EXECUTED', '9:ebe5424f34a8924f2c667cd12747156e', 'dropTable tableName=run_log; dropColumn columnName=workflow_type, tableName=workflow', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('fixed-spawned-connection-deletion', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.303201', 40, 'EXECUTED', '9:87a5d45cdbffb28536ed7ceac8c1cbcd', 'dropForeignKeyConstraint baseTableName=connection_to_spawn_ddl, constraintName=fk_connection_to_spawn_ddl_to_database_connection; addForeignKeyConstraint baseTableName=connection_to_spawn_ddl, constraintName=fk_connection_to_spawn_ddl_to_database_...', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('connections-amount', 'mstepachev@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.32706', 41, 'EXECUTED', '9:b7ce34f5003e31809e4ef8732476e5c5', 'addColumn tableName=workflow; update tableName=workflow; update tableName=workflow; modifyDataType columnName=source_pool_size, tableName=workflow; modifyDataType columnName=target_pool_size, tableName=workflow', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('layouts-table', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.342762', 42, 'EXECUTED', '9:6b0bbecc727f7179849e5907d7056985', 'createTable tableName=ui_table_layout', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('layouts-content-table', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.367862', 43, 'EXECUTED', '9:bcc77ae3b073714fa284f6dd018d26ac', 'createTable tableName=ui_table_layout_content; addForeignKeyConstraint baseTableName=ui_table_layout_content, constraintName=ui_table_layout_content_layout_id, referencedTableName=ui_table_layout', '', NULL, '4.29.1', NULL, NULL, '5887892942');
INSERT INTO public.databasechangelog VALUES ('layouts-table-createdby', 'ivan@synthesized.io', 'classpath:db/migration/dbchangelog.xml', '2024-09-09 13:18:13.381406', 44, 'EXECUTED', '9:6eb0066435f667d9849a6241af49514a', 'addColumn tableName=ui_table_layout', '', NULL, '4.29.1', NULL, NULL, '5887892942');


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.databasechangeloglock VALUES (1, false, NULL, NULL);


--
-- Data for Name: license; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: secretmanager_setup; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.secretmanager_setup VALUES ('vault', '{"uri":"http://vault:8200","token":"1234"}');


--
-- Data for Name: spawn_ddl; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: tag; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: tag_to_workflow; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: ui_table_layout; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.ui_table_layout VALUES (1, 'Default', 1);


--
-- Data for Name: ui_table_layout_content; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public."user" VALUES (1, 'test@synthesized.io', '$2a$10$s70PJ7s.oKUCWz3m46cCz.0dBDEC/20BST1lZ3Eq3v8Q9OLdukuR.', true, 'owner user', 'owner', 'OWNER', false, 'INTERNAL');
INSERT INTO public."user" VALUES (2, 'test-owner-role@synthesized.io', '$2a$10$s70PJ7s.oKUCWz3m46cCz.0dBDEC/20BST1lZ3Eq3v8Q9OLdukuR.', true, 'owner user', 'owner', 'OWNER', false, 'INTERNAL');
INSERT INTO public."user" VALUES (3, 'test-compliance-role@synthesized.io', '$2a$10$s70PJ7s.oKUCWz3m46cCz.0dBDEC/20BST1lZ3Eq3v8Q9OLdukuR.', true, 'compliance user', 'compliance', 'COMPLIANCE', false, 'INTERNAL');
INSERT INTO public."user" VALUES (4, 'test-administrator-role@synthesized.io', '$2a$10$s70PJ7s.oKUCWz3m46cCz.0dBDEC/20BST1lZ3Eq3v8Q9OLdukuR.', true, 'administrator user', 'admin', 'ADMINISTRATOR', false, 'INTERNAL');
INSERT INTO public."user" VALUES (5, 'test-user-role@synthesized.io', '$2a$10$s70PJ7s.oKUCWz3m46cCz.0dBDEC/20BST1lZ3Eq3v8Q9OLdukuR.', true, 'user user', 'user', 'USER', false, 'INTERNAL');


--
-- Data for Name: workflow; Type: TABLE DATA; Schema: public; Owner: apiuser
--

INSERT INTO public.workflow VALUES (1, 'Generation workflow', '2023-06-09 14:53:30.103527', '2023-06-09 14:55:53.617641', 1, 2, 1, 'default_config:
  mode: GENERATION
  target_ratio: 2

schema_creation_mode: DROP_AND_CREATE
safety_mode: RELAXED', 'INTERNAL', NULL, NULL, NULL, NULL, 20, 20);
INSERT INTO public.workflow VALUES (2, 'Masking workflow', '2023-06-09 14:53:30.103527', '2023-06-09 14:55:53.617641', 1, 2, 1, 'default_config:
  mode: MASKING

schema_creation_mode: DROP_AND_CREATE
safety_mode: RELAXED', 'INTERNAL', NULL, NULL, NULL, NULL, 20, 20);


--
-- Data for Name: workflow_activity_log; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: workflow_run; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Data for Name: workflow_run_step; Type: TABLE DATA; Schema: public; Owner: apiuser
--



--
-- Name: access_key_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.access_key_id_seq', 1, false);


--
-- Name: approval_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.approval_log_id_seq', 1, false);


--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 1, false);


--
-- Name: database_connection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.database_connection_id_seq', 2, true);


--
-- Name: spawn_ddl_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.spawn_ddl_id_seq', 1, false);


--
-- Name: tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.tag_id_seq', 1, false);


--
-- Name: ui_table_layout_content_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.ui_table_layout_content_id_seq', 1, false);


--
-- Name: ui_table_layout_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.ui_table_layout_id_seq', 1, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.user_id_seq', 6, true);


--
-- Name: workflow_activity_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.workflow_activity_log_id_seq', 1, false);


--
-- Name: workflow_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.workflow_id_seq', 3, false);


--
-- Name: workflow_run_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.workflow_run_id_seq', 1, false);


--
-- Name: workflow_run_step_id_seq; Type: SEQUENCE SET; Schema: public; Owner: apiuser
--

SELECT pg_catalog.setval('public.workflow_run_step_id_seq', 1, false);


--
-- Name: access_key access_key_key_key; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.access_key
    ADD CONSTRAINT access_key_key_key UNIQUE (key);


--
-- Name: access_key access_key_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.access_key
    ADD CONSTRAINT access_key_pkey PRIMARY KEY (id);


--
-- Name: agent_execution agent_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.agent_execution
    ADD CONSTRAINT agent_execution_pkey PRIMARY KEY (workflow_run_id);


--
-- Name: agent agent_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.agent
    ADD CONSTRAINT agent_pkey PRIMARY KEY (agent_id);


--
-- Name: approval_log approval_log_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.approval_log
    ADD CONSTRAINT approval_log_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: connection_to_spawn_ddl connection_to_spawn_ddl_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.connection_to_spawn_ddl
    ADD CONSTRAINT connection_to_spawn_ddl_pkey PRIMARY KEY (database_connection_id, spawn_ddl_id);


--
-- Name: database_connection database_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.database_connection
    ADD CONSTRAINT database_connection_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: license license_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.license
    ADD CONSTRAINT license_pkey PRIMARY KEY (id);


--
-- Name: secretmanager_setup secretmanager_setup_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.secretmanager_setup
    ADD CONSTRAINT secretmanager_setup_pkey PRIMARY KEY (id);


--
-- Name: spawn_ddl spawn_ddl_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.spawn_ddl
    ADD CONSTRAINT spawn_ddl_pkey PRIMARY KEY (id);


--
-- Name: tag tag_name_key; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_name_key UNIQUE (name);


--
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- Name: tag_to_workflow tag_to_workflow_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.tag_to_workflow
    ADD CONSTRAINT tag_to_workflow_pkey PRIMARY KEY (tag_id, workflow_id);


--
-- Name: ui_table_layout_content ui_table_layout_content_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.ui_table_layout_content
    ADD CONSTRAINT ui_table_layout_content_pkey PRIMARY KEY (id);


--
-- Name: ui_table_layout ui_table_layout_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.ui_table_layout
    ADD CONSTRAINT ui_table_layout_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: workflow_activity_log workflow_activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow_activity_log
    ADD CONSTRAINT workflow_activity_log_pkey PRIMARY KEY (id);


--
-- Name: workflow workflow_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (id);


--
-- Name: workflow_run workflow_run_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow_run
    ADD CONSTRAINT workflow_run_pkey PRIMARY KEY (id);


--
-- Name: workflow_run_step workflow_run_step_pkey; Type: CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow_run_step
    ADD CONSTRAINT workflow_run_step_pkey PRIMARY KEY (id);


--
-- Name: database_connection_uidx; Type: INDEX; Schema: public; Owner: apiuser
--

CREATE UNIQUE INDEX database_connection_uidx ON public.database_connection USING btree (name);


--
-- Name: user_name_uidx; Type: INDEX; Schema: public; Owner: apiuser
--

CREATE UNIQUE INDEX user_name_uidx ON public."user" USING btree (name);


--
-- Name: workflow_user_id_idx; Type: INDEX; Schema: public; Owner: apiuser
--

CREATE INDEX workflow_user_id_idx ON public.workflow USING btree (user_id);


--
-- Name: agent_execution agent_execution_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.agent_execution
    ADD CONSTRAINT agent_execution_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent(agent_id);


--
-- Name: agent_execution agent_execution_workflow_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.agent_execution
    ADD CONSTRAINT agent_execution_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_run(id);


--
-- Name: audit_log audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: database_connection database_connection_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.database_connection
    ADD CONSTRAINT database_connection_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- Name: access_key fk_access_keys_user_id; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.access_key
    ADD CONSTRAINT fk_access_keys_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: connection_to_spawn_ddl fk_connection_to_spawn_ddl_to_database_connection; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.connection_to_spawn_ddl
    ADD CONSTRAINT fk_connection_to_spawn_ddl_to_database_connection FOREIGN KEY (database_connection_id) REFERENCES public.database_connection(id) ON DELETE CASCADE;


--
-- Name: connection_to_spawn_ddl fk_connection_to_spawn_ddl_to_spawn_ddl; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.connection_to_spawn_ddl
    ADD CONSTRAINT fk_connection_to_spawn_ddl_to_spawn_ddl FOREIGN KEY (spawn_ddl_id) REFERENCES public.spawn_ddl(id);


--
-- Name: tag_to_workflow tag_to_workflow_tag_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.tag_to_workflow
    ADD CONSTRAINT tag_to_workflow_tag_fkey FOREIGN KEY (tag_id) REFERENCES public.tag(id) ON DELETE CASCADE;


--
-- Name: tag_to_workflow tag_to_workflow_workflow_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.tag_to_workflow
    ADD CONSTRAINT tag_to_workflow_workflow_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflow(id) ON DELETE CASCADE;


--
-- Name: ui_table_layout_content ui_table_layout_content_layout_id; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.ui_table_layout_content
    ADD CONSTRAINT ui_table_layout_content_layout_id FOREIGN KEY (layout_id) REFERENCES public.ui_table_layout(id) ON DELETE CASCADE;


--
-- Name: workflow workflow_input_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_input_connection_id_fkey FOREIGN KEY (input_connection_id) REFERENCES public.database_connection(id) ON DELETE SET NULL;


--
-- Name: workflow workflow_output_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_output_connection_id_fkey FOREIGN KEY (output_connection_id) REFERENCES public.database_connection(id) ON DELETE SET NULL;


--
-- Name: workflow_run_step workflow_run_step_workflow_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow_run_step
    ADD CONSTRAINT workflow_run_step_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_run(id);


--
-- Name: workflow workflow_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: apiuser
--

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--
